name: dart_classes
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.18.7 <3.0.0'

# dependencies:
#   auto_data_generator: ^0.0.3
#   path: ^1.8.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
